set -g @catppuccin_flavor "mocha"

set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_status_modules_right "battery date_time"

set -g @catppuccin_date_time_text "%a %d %b | %H:%M"

# Battery icons
# Discharging
set -g @batt_icon_charge_tier8 "󰁹"
set -g @batt_icon_charge_tier7 "󰂂"
set -g @batt_icon_charge_tier6 "󰂁"
set -g @batt_icon_charge_tier5 "󰂀"
set -g @batt_icon_charge_tier4 "󰁿"
set -g @batt_icon_charge_tier3 "󰁾"
set -g @batt_icon_charge_tier2 "󰁽"
set -g @batt_icon_charge_tier1 "󰁼"
set -g @batt_icon_charge_tier0 "󰁻"

# Charging
set -g @batt_icon_status_charging "󰂄"

# Fully charged
set -g @batt_icon_status_charged "󰁹"

# Unknown
set -g @batt_icon_status_unknown "󰂑"
