set -g status-position top
set -g status-style "bg=#0D1317,fg=#9CAAB3"

set -g status-left-length 30
set -g status-right-length 100

# Left
set -g status-left "#[fg=#3F8E9C,bold]#S#[default] "

# set -g status-right "#(~/.config/tmux/scripts/battery.sh) | %a %d %b | %H:%M"
# Right
set -g status-right "#[fg=#9CAAB3]#(~/.config/tmux/scripts/battery.sh) #[fg=#667580]| #[fg=#9CAAB3]%a %d %b #[fg=#667580]| #[fg=#D6DEE3]%H:%M"

# Windows
setw -g window-status-format " #I:#W "
setw -g window-status-style "bg=#151D22,fg=#667580"

setw -g window-status-current-format " #I:#W "
setw -g window-status-current-style "bg=#3F8E9C,fg=#070A0C,bold"

# Activity/Bells
setw -g window-status-activity-style "fg=#C9A86A,bold"
setw -g window-status-bell-style "fg=#C56E74,bold"

# Pane borders
set -g pane-border-style "fg=#202B31"
set -g pane-active-border-style "fg=#3F8E9C"

# Messages / command prompt
set -g message-style "bg=#202B31,fg=#D6DEE3"

# Copy mode
set -g mode-style "bg=#3F8E9C,fg=#070A0C"

